name: NES Clang builder

on:
  push:
    tags:
      - 'v*'

jobs:
  build-x64-linux:
    timeout-minutes: 360
    name: ${{ matrix.osversion }} ${{ matrix.arch }}
    runs-on: [self-hosted, linux, '${{ matrix.arch }}', dep-builder]
    strategy:
      fail-fast: false
      matrix:
        include:
          - osversion: ubuntu-18.04
            arch: "X64"
          - osversion: ubuntu-20.04
            arch: "X64"
          - osversion: ubuntu-22.04
            arch: "X64"
          - osversion: ubuntu-18.04
            arch: "arm64"
          - osversion: ubuntu-20.04
            arch: "arm64"
          - osversion: ubuntu-22.04
            arch: "arm64"    
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set output vars to the actual tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build Docker
        id: builddocker
        working-directory: ${{ github.workspace }}/docker/
        run: docker build  -t nes_clang_build_${{ matrix.osversion }} -f Dockerfile-${{ matrix.osversion }} .     
      - name: Build Clang
        id: installdeps
        run: |
          docker run -v ${{ github.workspace }}:/build_dir --rm nes_clang_build_${{ matrix.osversion }} \
          ./build_dir/build_ubuntu-${{ matrix.arch }}.sh
      - name: Compress artifacts
        id: compressdeps
        run: |
          7z a nes-clang-15-${{ matrix.osversion }}-${{ matrix.arch }}.7z clang -mx9 -aoa  
      - name: Release
        uses: softprops/action-gh-release@v1
        id: createrelease
        with:
          files: |
            nes-clang-15-${{ matrix.osversion }}-${{ matrix.arch }}.7z
      - name: Clean build artifacts
        id: cleanbuildartifacts
        if: always()
        run: |
          rm -rf llvm-project 
          rm -rf .git
          rm -rf clang
      - name: Remove docker image
        id: removedockerimage
        if: always()
        run: |
          test -n "$(docker image ls -q nes_clang_build_${{ matrix.osversion }})" && \
          docker image rm $(docker image ls -q nes_clang_build_${{ matrix.osversion }}) || \
          true  
  build-arm-osx:
    timeout-minutes: 360
    runs-on: [ self-hosted, macos, ARM64]
    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set output vars to the actual tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build OSX ARM Clang
        id: buildclang
        run: |
          ${{ github.workspace }}/build_osx-arm64.sh
        shell: bash
      - name: Compress artifacts
        id: compressdeps
        run: |
          7z a nes-clang-15-osx-arm64.7z clang -mx9 -aoa  
      - name: Release
        uses: softprops/action-gh-release@v1
        id: createrelease
        with:
          files: |
            nes-clang-15-osx-arm64.7z
      - name: Clean build artifacts
        id: cleanbuildartifacts
        if: always()
        run: |
          rm -rf clang
  build-x64-osx:
    timeout-minutes: 360
    runs-on: [ self-hosted, macos, X64, dep-builder ]
    steps:
      - uses: lukka/get-cmake@latest
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set output vars to the actual tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build OSX x64 Clang
        id: buildclang
        run: |
          ${{ github.workspace }}/build_osx-x64.sh
        shell: bash
      - name: Compress artifacts
        id: compressdeps
        run: |
          7z a nes-clang-15-osx-x64.7z clang -mx9 -aoa  
      - name: Release
        uses: softprops/action-gh-release@v1
        id: createrelease
        with:
          files: |
            nes-clang-15-osx-x64.7z
      - name: Clean build artifacts
        id: cleanbuildartifacts
        if: always()
        run: |
          rm -rf clang